config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Records routes
  get 'analyse_text', to: 'records#analyse_text'
  get 'analyse_audio', to: 'records#analyse_audio'

  resources :records, only: %i[new show create index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_one_attached :audio
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @record = Record.new
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # nethttp.rb
  require 'uri'
  require 'net/http'
  require 'securerandom'

  before_action :record_params, only: [:analyse_audio, :analyse_text]
  # uuid = SecureRandom.uuid
  # puts 'Your UUID is: ' + uuid

  def new
    @record = Record.new
  end

  def show
    @record = Record.find(params[:id])
  end

  def index
    @records = Record.where(user: current_user)
  end

  def create
    if params['record'].nil?
      redirect_to '/', alert: 'Por favor, selecione um arquivo de áudio para usar está funcionalidade.'
    elsif params['record']['audio'].content_type.starts_with?('audio') == false
      redirect_to '/', alert: 'Por favor, selecione um arquivo de áudio com extensão *.ogg .'
    else
      audio_file = params['record']['audio']
      uploaded_file = Cloudinary::Uploader.upload(audio_file, resource_type: 'video', is_audio: true)
      filename = "#{uploaded_file['public_id']}.ogg"
      download_url = uploaded_file['secure_url']
      # If it breaks, check Cloudinary username in the url
      # download_url = "https://res.cloudinary.com/alecastello/video/upload/fl_attachment/v#{uploaded_file['version']}/#{filename}"
      start = Time.now
      api_response = api_request({ audio_file: download_url, filename: filename }, 'analyse_audio')
      api_response_encoded = api_response.force_encoding("UTF-8")
      parsed_response = JSON.parse(api_response_encoded)
      finish = Time.now
      diff = finish - start
      if current_user
        @record = Record.create filename: filename,
                                analysis: parsed_response['textAnalysis'],
                                user: current_user,
                                nickname: filename,
                                transcription: parsed_response['transcribedText'],
                                analysis_time: diff,
                                audio_url: download_url
        redirect_to @record
      else
        redirect_to result(response)
      end
    end
  end

  def analyse_text
    user_text = params['text_area']
    request_params = { user_text: user_text }
    method = 'analyse_text'
    start = Time.now
    response = api_request(request_params, method).force_encoding("UTF-8")
    finish = Time.now
    diff = finish - start
    if current_user
      @record = Record.create transcription: user_text,
                              analysis: response,
                              user: current_user,
                              nickname: DateTime.now.strftime("%Y%m%d%H%M%S"),
                              analysis_time: diff
      redirect_to @record
    else
      redirect_to result(response)
    end
  end

  def result(response)
    @response = response
  end

  private

  def api_request(request_params, method)
    uri = URI("https://api.hear4.me/#{method}")
    uri.query = URI.encode_www_form(request_params)
    res = Net::HTTP.get_response(uri)
    res.body if res.is_a?(Net::HTTPSuccess)
  end

  def record_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>hear4me</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer', class: "mt-auto" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(#023047AA,#02304700), url(https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container" style='width:60%'>
    <h1>Use seu tempo para o que <strong>realmente importa</strong>!</h1>
    <p>Deixe que a gente te resume aquele monte de áudio que você recebeu hoje.</p>
    <br>
    <h2>Análise de Áudio</h2>
    <%= simple_form_for @record do |f| %>
      <%= f.input :audio, label:'Selecione um arquivo de áudio', as: :file, accept:'audio/*', required: true %>
      <%= f.submit "Enviar áudio", class:"btn btn-flat"%>
    <% end %>
    <div>
        <br>
        <br>
        <br>
        <br>
      <div class='mt-5 form-group'>
        <h1>Caramba, mas recebeu um textão? </h1>
        <p>A gente também te ajuda com isso 👀</p>
        <br>
        <h2>Análise de Texto</h2>
        <%= form_with url: analyse_text_path, method: :get, remote: true do |f| %>
          <br>
          <%= f.text_field :text_area, placeholder: 'Insira um texto para análise aqui',  class:'form-control' %>
          <br>
          <%= f.submit "Enviar texto", class:'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/records/analyse_text.html.erb
<%= @response %>

app/views/records/result.html.erb
<p>Nome:
<%= @response.nickname %>

<p>Transcription:
<%= @response.transcription %>

<p>Analysis:
<%= @response.analysis %>

<p>Analysis Time:
<%= @response.analysis_time %>

app/views/records/show.html.erb
<div class='m-5'>
  <div class="card border-secondary m-auto" style="max-width: 80%;">
    <div class="card-header d-flex align-items-center">
      <% if @record.audio_url %>
        <%= audio_tag(@record.audio_url, autoplay: false, controls: true) %>
      <% end %>
      &nbsp
      <%= @record.created_at.strftime('Data: %d/%m/%Y, Hora: %H:%M:%S') %>
    </div>
    <div class="card-body text-secondary">
      <h5 class="card-title">Transcrição</h5>
      <p class="card-text"><%= @record.transcription %></p>
      <h5 class="card-title">Análise</h5>
      <p class="card-text"><%= @record.analysis %></p>
      <h5 class="card-title">Tempo de análise</h5>
      <p class="card-text"><%= @record.analysis_time.round 2 %> segundos</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class='row'>
    <div class='col-lg-3'>
      <h4><strong>hear4me</strong></h4>
    </div>
    <div class='col-lg-3'>
      <%# <p> Quem somos
      <p> Como Funciona
      <p> Privacidade
      <p> Vagas %>
    </div>
  </div>
  <div class="footer-links">
    <a href="https://github.com/alexandrecastello/python-hear4me"><i class="fab fa-github"></i></a>
    <a href="/"><i class="fab fa-instagram"></i></a>
    <a href="/"><i class="fab fa-facebook"></i></a>
    <a href="/"><i class="fab fa-twitter"></i></a>
    <a href="/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2022 hear4me, Inc.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <div class="logo">hear4me</div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Seus registros", '', class: "nav-link" %>
          </li>          
          <li class="nav-item">
            <strong>
              <%= link_to "Seja Premium", '', class: "nav-link" %>
            </strong>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/alexandrecastello", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Seus Registros", "#", class: "dropdown-item" %>
              <%= link_to "Seja Premium", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>